### ISSUE TITLE
Export not working on prod

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#107]
When you go to a waiting room to export the list of people it fails
```
[2016-03-17 15:35:18] production.ERROR: exception 'ErrorException' with message 'Undefined property: stdClass::$last_name' in /var/www/gladiator/releases/20160317145926/app/Services/Manager.php:48
Stack trace:
#0 /var/www/gladiator/releases/20160317145926/app/Services/Manager.php(48): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined prope...', '/var/www/gladia...', 48, Array)
#1 /var/www/gladiator/releases/20160317145926/app/Http/Controllers/WaitingRoomsController.php(141): Gladiator\Services\Manager->exportCSV(Object(Gladiator\Models\WaitingRoom))
#2 [internal function]: Gladiator\Http\Controllers\WaitingRoomsController->export(Object(Gladiator\Models\WaitingRoom))
#3 /var/www/gladiator/releases/20160317145926/bootstrap/cache/compiled.php(9236): call_user_func_array(Array, Array)
#4 /var/www/gladiator/releases/20160317145926/bootstrap/cache/compiled.php(9298): Illuminate\Routing\Controller->callAction('export', Array)
#5 /var/www/gladiator/releases/20160317145926/bootstrap/cache/compiled.php(9278): Illuminate\Routing\ControllerDispatcher->call(Object(Gladiator\Http\Controllers\WaitingRoomsController), Object(Illuminate\Routing\Route), 'export')
#6 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#7 /var/www/gladiator/releases/20160317145926/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#8 /var/www/gladiator/releases/20160317145926/app/Http/Middleware/CheckRole.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 [internal function]: Gladiator\Http\Middleware\CheckRole->handle(Object(Illuminate\Http\Request), Object(Closure), 'admin', 'staff')
#10 /var/www/gladiator/releases/20160317145926/bootstrap/cache/compiled.php(9765): call_user_func_array(Array, Array)
#11 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/gladiator/releases/20160317145926/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /var/www/gladiator/releases/20160317145926/app/Http/Middleware/Authenticate.php(28): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 [internal function]: Gladiator\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /var/www/gladiator/releases/20160317145926/bootstrap/cache/compiled.php(9765): call_user_func_array(Array, Array)
#16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/gladiator/releases/20160317145926/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/gladiator/releases/20160317145926/bootstrap/cache/compiled.php(9755): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /var/www/gladiator/releases/20160317145926/bootstrap/cache/compiled.php(9279): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /var/www/gladiator/releases/20160317145926/bootstrap/cache/compiled.php(9266): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Gladiator\Http\Controllers\WaitingRoomsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'export')
#22 /var/www/gladiator/releases/20160317145926/bootstrap/cache/compiled.php(8355): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routinglaravel.log
```

**Comment by deadlybutter** [comment]
@angaither should I switch focus to this?

**Comment by deadlybutter** [comment]
yeah confirmed it works on prod now
