### ISSUE TITLE
welcome email issues 

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#292]
seeing a lot of these

```
2016-05-03 20:47:14] production.ERROR: exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [] does not comply with RFC 2822, 3.6.2.' in /var/www/gladiator/releases/20160502193114/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:348
Stack trace:
#0 /var/www/gladiator/releases/20160502193114/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(263): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('')
#1 /var/www/gladiator/releases/20160502193114/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2 /var/www/gladiator/releases/20160502193114/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3 /var/www/gladiator/releases/20160502193114/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderFactory.php(58): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4 /var/www/gladiator/releases/20160502193114/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderSet.php(68): Swift_Mime_SimpleHeaderFactory->createMailboxHeader('To', Array)
#5 /var/www/gladiator/releases/20160502193114/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(323): Swift_Mime_SimpleHeaderSet->addMailboxHeader('To', Array)
#6 /var/www/gladiator/releases/20160502193114/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(299): Swift_Mime_SimpleMessage->setTo(Array)
#7 /var/www/gladiator/releases/20160502193114/vendor/laravel/framework/src/Illuminate/Mail/Message.php(137): Swift_Mime_SimpleMessage->addTo(NULL, NULL)
#8 /var/www/gladiator/releases/20160502193114/vendor/laravel/framework/src/Illuminate/Mail/Message.php(85): Illuminate\Mail\Message->addAddresses(NULL, NULL, 'To')
#9 /var/www/gladiator/releases/20160502193114/vendor/jeremeamia/SuperClosure/src/SerializableClosure.php(210) : eval()'d code(3): Illuminate\Mail\Message->to(NULL, NULL)
#10 [internal function]: {closure}(Object(Illuminate\Mail\Message))
#11 /var/www/gladiator/releases/20160502193114/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(401): call_user_func(Object(Closure), Object(Illuminate\Mail\Message))
#12 /var/www/gladiator/releases/20160502193114/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(165): Illuminate\Mail\Mailer->callMessageBuilder(Object(Closure), Object(Illuminate\Mail\Message))
#13 /var/www/gladiator/releases/20160502193114/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(278): Illuminate\Mail\Mailer->send('messages.welcom...', Array, Object(Closure))
#14 /var/www/gladiator/releases/20160502193114/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Mail\Mailer->handleQueuedMessage(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#15 /var/www/gladiator/releases/20160502193114/vendor/laravel/framework/src/Illuminate/Queue/Jobs/RedisJob.php(50): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
```

**Comment by angaither** [comment]
we should log the people who are failing and see what's going on

**Comment by deadlybutter** [comment]
agree, not sure how cause it doesn't seem to fail until we try to send it. try catch..?

**Comment by sbsmith86** [comment]
Actually it looks like we do see the "To" address that is failing

```
#8 /var/www/gladiator/releases/20160502193114/vendor/laravel/framework/src/Illuminate/Mail/Message.php(85): Illuminate\Mail\Message->addAddresses(NULL, NULL, 'To')
```

But the user is null. So gotta figure out the correct place to catch the error so we can grab the user.

**Comment by sbsmith86** [comment]
Update on this. Deployed #294 to QA and welcome emails still seem to be sending. 

I did see an issue when I signed up for a competition from my admin account. I don't know what happened and I think I need to be able to remove myself from the waiting room in order to test this further and see if there was an actual issue, or just a one off thing. Anyway this is the error I saw:

```
[2016-05-04 14:44:55] production.DEBUG: made an API request {"method":"GET","path":"users/email/ssmith@dosomething.org","options":{"query":[]}}
[2016-05-04 14:44:56] production.DEBUG: made an API request {"method":"GET","path":"campaigns/1334","options":{"query":[]}}
**[2016-05-04 14:44:58] production.ALERT: User email is not valid {"id":"559442cca59dbfc9578b4bf4","email":null}**
```

**Comment by angaither** [comment]
@sbsmith86 I wonder if it's users who are already in gladiator are getting those `null` emails. 
I also just tried with my admin account and got nothing

I also tried with a user who is in a different comp and got nothing

**Comment by sbsmith86** [comment]
@angaither hmm maybe! cause i got the welcome email when I created a new account in phoenix and signed up. but my admin account did not work.

**Comment by sbsmith86** [comment]
OK I think I got this working after #298. Added some better logging, also. 

So now when signing up for a competition with an existing account we get an email!!!

```
[2016-05-04 17:36:37] production.DEBUG: Gladiator\Http\Controllers\Api\UsersController -- Storing user {"user":"[object] (Gladiator\\Models\\User: {\"id\":\"559442cca59dbfc9578b4bf4\",\"role\":\"admin\",\"created_at\":\"2016-03-08 16:32:27\",\"updated_at\":\"2016-03-08 16:32:27\"})"}
[2016-05-04 17:36:37] production.DEBUG: Gladiator\Http\Controllers\Api\UsersController -- Sending welcome email {"user":"[object] (stdClass: {\"id\":\"559442cca59dbfc9578b4bf4\",\"_id\":\"559442cca59dbfc9578b4bf4\",\"first_name\":\"Shae\",\"last_name\":null,\"last_initial\":\"\",\"photo\":null,\"email\":\"ssmith@dosomething.org\",\"mobile\":\"9175171438\",\"interests\":null,\"birthdate\":\"1986-03-11 00:00:00\",\"addr_street1\":\"\",\"addr_street2\":\"\",\"addr_city\":\"\",\"addr_state\":\"\",\"addr_zip\":\"\",\"source\":\"phoenix\",\"mobilecommons_id\":null,\"parse_installation_ids\":null,\"mobilecommons_status\":null,\"language\":\"\",\"country\":\"US\",\"drupal_id\":\"1702694\",\"updated_at\":\"2016-05-02T16:45:41+0000\",\"created_at\":\"2014-11-14T19:45:11+0000\",\"role\":\"admin\"})"}
```

![image](https://cloud.githubusercontent.com/assets/1700409/15023225/9aea9e30-11fd-11e6-84f3-4260445f4617.png)

Same when signing up as a new user: 

```
[2016-05-04 17:38:50] production.DEBUG: Gladiator\Http\Controllers\Api\UsersController -- Storing user {"user":"[object] (Gladiator\\Models\\User: {\"id\":\"572a33aba59dbf205b8b4593\",\"role\":null,\"updated_at\":\"2016-05-04 17:38:50\",\"created_at\":\"2016-05-04 17:38:50\"})"}
[2016-05-04 17:38:51] production.DEBUG: Gladiator\Http\Controllers\Api\UsersController -- Sending welcome email {"user":"[object] (stdClass: {\"id\":\"572a33aba59dbf205b8b4593\",\"_id\":\"572a33aba59dbf205b8b4593\",\"first_name\":\"YourMama\",\"last_name\":null,\"last_initial\":\"\",\"photo\":null,\"email\":\"ssmith+mama@dosomething.org\",\"mobile\":null,\"interests\":null,\"birthdate\":\"1986-03-11 00:00:00\",\"addr_street1\":null,\"addr_street2\":null,\"addr_city\":null,\"addr_state\":null,\"addr_zip\":null,\"source\":null,\"mobilecommons_id\":null,\"parse_installation_ids\":null,\"mobilecommons_status\":null,\"language\":\"en\",\"country\":\"US\",\"drupal_id\":\"1707166\",\"updated_at\":\"2016-05-04T17:38:52+0000\",\"created_at\":\"2016-05-04T17:38:51+0000\",\"role\":null})"}
```

![image](https://cloud.githubusercontent.com/assets/1700409/15023300/ed68f51c-11fd-11e6-8de2-d1ed4fe807ee.png)

**Comment by sbsmith86** [comment]
@angaither  i'm not sure how useful logging is since we truncate the log. Maybe we should think about some stathatting stuff?

**Comment by angaither** [comment]
@sbsmith86 I think we def don't need to log this stuff (in fact I set turn off every log api request to false) on prod

**Comment by sbsmith86** [comment]
@angaither well the only reason it could be useful is when we got errors like we got the other day, so we know what email was failing. but i think this stuff should fix it up, so maybe it's not a big deal. Should I deploy to prod?

**Comment by angaither** [comment]
@sbsmith86 yup! sorry I mean we should be logging errors, not all the requests

**Comment by angaither** [comment]
leaving open, I rolled back the changes in #298 so this is back to the previous state
of 
users who already opted in to a competition will not get a second welcome email for a different competition

**Comment by sbsmith86** [comment]
@angaither should i keep looking into this? or is someone else on it.

**Comment by angaither** [comment]
@sbsmith86 do you mind taking another stab on this with @weerd maybe a lil purrprogrammming

**Comment by angaither** [comment]
things are lookin 👌
